apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
  name: default
  namespace: default
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel
    namespace: knative-eventing
  delivery:
    backoffDelay: PT0.2S
    backoffPolicy: exponential
    retry: 10
---
apiVersion: v1
data:
  backend: zipkin
  debug: "true"
  sample-rate: "1.0"
  zipkin-endpoint: http://simplest-collector.default.svc.cluster.local:9411
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.13.1
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
  name: config-tracing
  namespace: knative-eventing
